package(default_visibility = ["//visibility:public"])

exports_files([
    "BUILD.bazel",
    "LICENSE",
    "MODULE.bazel",
    "README.md",
    "WORKSPACE.bazel",
])

filegroup(
    name = "module_files",
    srcs = [
        "BUILD.bazel",
        "LICENSE",
        "MODULE.bazel",
        "README.md",
        "WORKSPACE.bazel",
    ],
)
